In [10]:
import numpy as np

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

def softmax2(x):
    e_x = np.exp(x - np.max(x))
    return e_x / np.sum(e_x, axis=0)

scores = np.array([[1, 2, 3, 6],
                     [2, 4, 5, 6],
                     [3, 8, 7, 6]])
print(softmax(scores))
print(sum(softmax(scores)))

print(softmax2(scores))
print(sum(softmax2(scores)))



[[0.09003057 0.00242826 0.01587624 0.33333333]
 [0.24472847 0.01794253 0.11731043 0.33333333]
 [0.66524096 0.97962921 0.86681333 0.33333333]]
[1. 1. 1. 1.]
[[0.09003057 0.00242826 0.01587624 0.33333333]
 [0.24472847 0.01794253 0.11731043 0.33333333]
 [0.66524096 0.97962921 0.86681333 0.33333333]]
[1. 1. 1. 1.]
